#############################################################################
# Makefile for building: QtProjectFile.js
# Generated by qmake (3.1) (Qt 5.12.0)
# Project:  QtProjectFile.pro
# Template: app
# Command: /home/somas/Qt12_wasm/5.12.0/Src/qtbase/bin/qmake -o Makefile QtProjectFile.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = emcc
CXX           = em++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_QML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -s USE_LIBPNG=1 -s USE_FREETYPE=1 -s USE_ZLIB=1 -O3 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -s USE_LIBPNG=1 -s USE_FREETYPE=1 -s USE_ZLIB=1 -O3 -std=gnu++1y -Wall -W $(DEFINES)
INCPATH       = -I. -I../../Qt12_wasm/5.12.0/Src/qtdeclarative/include -I../../Qt12_wasm/5.12.0/Src/qtbase/include -I../../Qt12_wasm/5.12.0/Src/qtdeclarative/include/QtQuick -I../../Qt12_wasm/5.12.0/Src/qtbase/include/QtQuick -I../../Qt12_wasm/5.12.0/Src/qtdeclarative/include/QtQml -I../../Qt12_wasm/5.12.0/Src/qtbase/include/QtQml -I../../Qt12_wasm/5.12.0/Src/qtbase/include/QtGui -I../../Qt12_wasm/5.12.0/Src/qtbase/include/QtNetwork -I../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore -I. -I/home/somas/.emscripten_ports/openssl/include -I../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/wasm-emscripten
QMAKE         = /home/somas/Qt12_wasm/5.12.0/Src/qtbase/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/somas/Qt12_wasm/5.12.0/Src/qtbase/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/somas/Qt12_wasm/5.12.0/Src/qtbase/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = QtProjectFile.js1.0.0
DISTDIR = /home/somas/ChessNewGeneration/ChessNewGeneration/.tmp/QtProjectFile.js1.0.0
LINK          = em++
LFLAGS        = -s WASM=1 -s FULL_ES2=1 -s ALLOW_MEMORY_GROWTH=1 -s USE_WEBGL2=1 -s NO_EXIT_RUNTIME=0 -s ERROR_ON_UNDEFINED_SYMBOLS=1 --bind -s "BINARYEN_METHOD='native-wasm'" -s "BINARYEN_TRAP_MODE='clamp'" -O3 -L/home/somas/Qt12_wasm/5.12.0/Src/qtbase/lib -lqtfreetype -s USE_LIBPNG=1
LIBS          = $(SUBLIBS) -L/home/somas/Qt12_wasm/5.12.0/Src/qtbase/plugins/platforms -L/home/somas/Qt12_wasm/5.12.0/Src/qtbase/lib -s USE_ZLIB=1 -s USE_LIBPNG=1 -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -lwasm -lQt5EventDispatcherSupport -s -s -s -s -lQt5FontDatabaseSupport -s -s -s -s -lqtfreetype -s -s -lQt5EglSupport -s -s -s -s -s -s -s -s -L/home/somas/Qt12_wasm/5.12.0/Src/qtbase/plugins/imageformats -lqgif -s -s -s -s -lqicns -s -s -s -s -lqico -s -s -s -s -lqjpeg -s -s -s -s -lqtga -s -s -s -s -lqtiff -s -s -s -s -s -lqwbmp -s -s -s -s -lqwebp -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -L/home/somas/Qt12_wasm/5.12.0/Src/qtbase/qml/QtQuick.2 -lqtquick2plugin -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -s -L/home/somas/Qt12_wasm/5.12.0/Src/qtbase/qml/QtQuick/Window.2 -lwindowplugin -lQt5Quick -s -s -s -s -s -s -s -s -s -s -s -s -lQt5Qml -s -s -s -lQt5Gui -s -s -lqtharfbuzz -s -lQt5Network -s -s -lQt5Core -s -lqtpcre2   
AR            = emar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp /home/somas/ChessNewGeneration/ChessNewGeneration/qtprojectfile.js_plugin_import.cpp \
		/home/somas/ChessNewGeneration/ChessNewGeneration/qtprojectfile.js_qml_plugin_import.cpp \
		qrc_qml.cpp \
		qrc_resources.cpp \
		moc_ChessInterface.cpp
OBJECTS       = main.o \
		qtprojectfile.js_plugin_import.o \
		qtprojectfile.js_qml_plugin_import.o \
		qrc_qml.o \
		qrc_resources.o \
		moc_ChessInterface.o
DIST          = ../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/spec_pre.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/common/sanitize.conf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/common/gcc-base.conf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/common/clang.conf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/qconfig.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_ext_freetype.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_ext_harfbuzz.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_ext_openwnn.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_ext_pcre2.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_ext_pinyin.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_ext_tcime.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_bluetooth.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_bluetooth_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_charts.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_charts_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_charts.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_core.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_datavisualization.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_datavisualization_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_gamepad.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_gamepad_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_gui.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_multimedia.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_multimedia_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_multimediawidgets.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_multimediawidgets_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_network.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_networkauth.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_networkauth_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_nfc.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_nfc_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_purchasing.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_purchasing_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_qml.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_qml_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_qml.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_qmldevtools_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_qmltest.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_qmltest_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quick.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quick_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_quick.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quickcontrols2.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quickcontrols2_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quickparticles_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quickshapes_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quicktemplates2_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quickwidgets.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quickwidgets_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_remoteobjects.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_remoteobjects_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_repparser.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_repparser_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_script.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_script_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_script.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_scripttools.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_scripttools_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_scxml.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_scxml_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_sensors.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_sensors_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_svg.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_svg_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_svg.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_texttospeech.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_texttospeech_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_uiplugin.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_uitools.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_uitools_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_virtualkeyboard.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_virtualkeyboard_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_webchannel.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_webchannel_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_websockets.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_websockets_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_webview.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_webview_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_webview.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_xml.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_xmlpatterns.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_xmlpatterns_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_zlib_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_eglvideonode.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qgif.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qicns.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qico.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qsvg.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtga.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtiff.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_hangul.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_openwnn.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_pinyin.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_tcime.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_thai.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qwebgl.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qwebp.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_wasm.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_tool_syncqt.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_tool_xmlpatterns.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_tool_xmlpatternsvalidator.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/qt_functions.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/qt_config.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/wasm-emscripten/qmake.conf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/exclusive_builds.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/toolchain.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/default_pre.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/resolve_config.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/default_post.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/wasm/wasm.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/warn_on.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/plugins/platforms/libwasm.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/qt.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/wasm/qt.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/resources.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/moc.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/unix/opengl.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/unix/thread.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/qmake_use.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/file_copies.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/testcase_targets.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/exceptions.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/yacc.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/lex.prf \
		QtProjectFile.pro ChessGame.h \
		ChessInterface.h \
		ChessPieces.h \
		Chessboard.h \
		Move.h \
		Piece.h \
		Player.h \
		Position.h main.cpp
QMAKE_TARGET  = QtProjectFile.js
DESTDIR       = 
TARGET        = QtProjectFile.js


first: all
####### Build rules

QtProjectFile.js: /home/somas/Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5Quick.a /home/somas/Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5Qml.a /home/somas/Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5Gui.a /home/somas/Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5Network.a /home/somas/Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5Core.a $(OBJECTS)  apphtml appjs appsvg
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QtProjectFile.pro ../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/wasm-emscripten/qmake.conf ../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/spec_pre.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/common/sanitize.conf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/common/gcc-base.conf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/common/clang.conf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/qconfig.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_ext_freetype.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_ext_harfbuzz.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_ext_openwnn.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_ext_pcre2.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_ext_pinyin.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_ext_tcime.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_bluetooth.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_bluetooth_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_charts.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_charts_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_charts.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_core.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_datavisualization.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_datavisualization_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_gamepad.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_gamepad_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_gui.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_multimedia.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_multimedia_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_multimediawidgets.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_multimediawidgets_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_network.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_networkauth.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_networkauth_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_nfc.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_nfc_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_purchasing.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_purchasing_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_qml.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_qml_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_qml.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_qmldevtools_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_qmltest.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_qmltest_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quick.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quick_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_quick.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quickcontrols2.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quickcontrols2_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quickparticles_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quickshapes_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quicktemplates2_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quickwidgets.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quickwidgets_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_remoteobjects.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_remoteobjects_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_repparser.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_repparser_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_script.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_script_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_script.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_scripttools.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_scripttools_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_scxml.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_scxml_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_sensors.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_sensors_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_svg.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_svg_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_svg.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_texttospeech.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_texttospeech_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_uiplugin.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_uitools.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_uitools_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_virtualkeyboard.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_virtualkeyboard_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_webchannel.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_webchannel_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_websockets.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_websockets_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_webview.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_webview_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_webview.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_xml.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_xmlpatterns.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_xmlpatterns_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_zlib_private.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_eglvideonode.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qgif.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qicns.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qico.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qsvg.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtga.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtiff.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_hangul.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_openwnn.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_pinyin.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_tcime.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_thai.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qwebgl.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qwebp.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_wasm.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_tool_syncqt.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_tool_xmlpatterns.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_tool_xmlpatternsvalidator.pri \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/qt_functions.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/qt_config.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/wasm-emscripten/qmake.conf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/exclusive_builds.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/toolchain.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/default_pre.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/resolve_config.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/default_post.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/wasm/wasm.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/warn_on.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/plugins/platforms/libwasm.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/qt.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/wasm/qt.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/resources.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/moc.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/unix/opengl.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/unix/thread.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/qmake_use.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/file_copies.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/testcase_targets.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/exceptions.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/yacc.prf \
		../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/lex.prf \
		QtProjectFile.pro \
		qml.qrc \
		resources.qrc \
		../../Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5EventDispatcherSupport.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5FontDatabaseSupport.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/lib/libqtfreetype.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5EglSupport.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5Gui.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/lib/libqtharfbuzz.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5Core.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/lib/libqtpcre2.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/plugins/imageformats/libqgif.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/plugins/imageformats/libqicns.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/plugins/imageformats/libqico.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/plugins/imageformats/libqjpeg.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/plugins/imageformats/libqtga.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/plugins/imageformats/libqtiff.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/plugins/imageformats/libqwbmp.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/plugins/imageformats/libqwebp.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5Quick.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5Qml.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5Network.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/qml/QtQuick.2/libqtquick2plugin.prl \
		../../Qt12_wasm/5.12.0/Src/qtbase/qml/QtQuick/Window.2/libwindowplugin.prl
	$(QMAKE) -o Makefile QtProjectFile.pro
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/spec_pre.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/common/sanitize.conf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/common/gcc-base.conf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/common/clang.conf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/qconfig.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_ext_freetype.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_ext_harfbuzz.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_ext_openwnn.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_ext_pcre2.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_ext_pinyin.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_ext_tcime.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_bluetooth.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_bluetooth_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_charts.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_charts_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_charts.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_core.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_core_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_datavisualization.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_datavisualization_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_egl_support_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_gamepad.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_gamepad_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_gui.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_multimedia.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_multimedia_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_multimediawidgets.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_multimediawidgets_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_network.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_network_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_networkauth.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_networkauth_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_nfc.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_nfc_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_nfc.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_opengl.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_purchasing.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_purchasing_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_qml.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_qml_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_qml.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_qmldevtools_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_qmltest.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_qmltest_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quick.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quick_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_quick.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quickcontrols2.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quickcontrols2_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quickparticles_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quickshapes_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quicktemplates2_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quickwidgets.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_quickwidgets_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_remoteobjects.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_remoteobjects_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_repparser.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_repparser_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_repparser.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_script.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_script_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_script.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_scripttools.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_scripttools_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_scxml.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_scxml_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_scxml.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_sensors.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_sensors_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_sensors.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_service_support_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_svg.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_svg_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_svg.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_testlib.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_texttospeech.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_texttospeech_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_uiplugin.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_uitools.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_uitools_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_uitools.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_virtualkeyboard.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_virtualkeyboard_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_webchannel.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_webchannel_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_websockets.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_websockets_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_websockets.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_webview.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_webview_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_webview.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_widgets.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_xml.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_xmlpatterns.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules-inst/qt_lib_xmlpatterns_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_lib_zlib_private.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_eglvideonode.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qgif.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qicns.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qico.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qjpeg.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qsvg.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtga.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtiff.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_hangul.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_openwnn.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_pinyin.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_tcime.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboard_thai.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qwbmp.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qwebgl.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_qwebp.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_plugin_wasm.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_tool_syncqt.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_tool_xmlpatterns.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/modules/qt_tool_xmlpatternsvalidator.pri:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/qt_functions.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/qt_config.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/wasm-emscripten/qmake.conf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/exclusive_builds.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/toolchain.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/default_pre.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/resolve_config.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/default_post.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/wasm/wasm.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/warn_on.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/plugins/platforms/libwasm.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/qt.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/wasm/qt.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/resources.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/moc.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/unix/opengl.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/unix/thread.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/qmake_use.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/file_copies.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/testcase_targets.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/exceptions.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/yacc.prf:
../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/lex.prf:
QtProjectFile.pro:
qml.qrc:
resources.qrc:
../../Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5EventDispatcherSupport.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5FontDatabaseSupport.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/lib/libqtfreetype.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5EglSupport.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5Gui.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/lib/libqtharfbuzz.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5Core.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/lib/libqtpcre2.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/plugins/imageformats/libqgif.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/plugins/imageformats/libqicns.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/plugins/imageformats/libqico.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/plugins/imageformats/libqjpeg.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/plugins/imageformats/libqtga.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/plugins/imageformats/libqtiff.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/plugins/imageformats/libqwbmp.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/plugins/imageformats/libqwebp.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5Quick.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5Qml.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/lib/libQt5Network.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/qml/QtQuick.2/libqtquick2plugin.prl:
../../Qt12_wasm/5.12.0/Src/qtbase/qml/QtQuick/Window.2/libwindowplugin.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile QtProjectFile.pro

qmake_all: FORCE


all: Makefile QtProjectFile.js

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ChessGame.h ChessInterface.h ChessPieces.h Chessboard.h Move.h Piece.h Player.h Position.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) *.html *.js *.wasm /home/somas/ChessNewGeneration/ChessNewGeneration/qtprojectfile.js_plugin_import.cpp /home/somas/ChessNewGeneration/ChessNewGeneration/qtprojectfile.js_qml_plugin_import.cpp .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

apphtml: /home/somas/Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/wasm/../../../src/plugins/platforms/wasm/wasm_shell.html
	sed -e s/APPNAME/QtProjectFile/g /home/somas/Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/wasm/../../../src/plugins/platforms/wasm/wasm_shell.html > /home/somas/ChessNewGeneration/ChessNewGeneration/QtProjectFile.html

appjs: /home/somas/Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/wasm/../../../src/plugins/platforms/wasm/qtloader.js
	cp -f /home/somas/Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/wasm/../../../src/plugins/platforms/wasm/qtloader.js /home/somas/ChessNewGeneration/ChessNewGeneration

appsvg: /home/somas/Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/wasm/../../../src/plugins/platforms/wasm/qtlogo.svg
	cp -f /home/somas/Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/wasm/../../../src/plugins/platforms/wasm/qtlogo.svg /home/somas/ChessNewGeneration/ChessNewGeneration

shellfiles: apphtml appjs appsvg

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_apphtml_make_all:
compiler_apphtml_clean:
	-$(DEL_FILE) QtProjectFile.html
compiler_appjs_make_all:
compiler_appjs_clean:
	-$(DEL_FILE) qtloader.js
compiler_appsvg_make_all:
compiler_appsvg_clean:
	-$(DEL_FILE) qtlogo.svg
compiler_rcc_make_all: qrc_qml.cpp qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp qrc_resources.cpp
qrc_qml.cpp: qml.qrc \
		../../Qt12_wasm/5.12.0/Src/qtbase/bin/rcc \
		main.qml
	/home/somas/Qt12_wasm/5.12.0/Src/qtbase/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

qrc_resources.cpp: resources.qrc \
		../../Qt12_wasm/5.12.0/Src/qtbase/bin/rcc \
		images/pawn_black.png \
		images/rook_white.png \
		images/rook_black.png \
		images/king_white.png \
		images/king_black.png \
		images/queen_white.png \
		images/knight_white.png \
		images/knight_black.png \
		images/queen_black.png \
		images/bishop_white.png \
		images/bishop_black.png \
		images/pawn_white.png
	/home/somas/Qt12_wasm/5.12.0/Src/qtbase/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/data/dummy.cpp
	em++ -pipe -s USE_LIBPNG=1 -s USE_FREETYPE=1 -s USE_ZLIB=1 -O3 -std=gnu++1y -Wall -W -dM -E -o moc_predefs.h ../../Qt12_wasm/5.12.0/Src/qtbase/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_ChessInterface.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ChessInterface.cpp
moc_ChessInterface.cpp: ../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/QObject \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qobject.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/kernel/qobject.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qobjectdefs.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/kernel/qobjectdefs.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qnamespace.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qnamespace.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qglobal.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qglobal.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qconfig-bootstrapped.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qconfig-bootstrapped.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qconfig.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qconfig.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qtcore-config.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/qtcore-config.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qsystemdetection.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qsystemdetection.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qprocessordetection.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qprocessordetection.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qcompilerdetection.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qcompilerdetection.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qtypeinfo.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qtypeinfo.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qsysinfo.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qsysinfo.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qlogging.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qlogging.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qflags.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qflags.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qatomic.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/thread/qatomic.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qbasicatomic.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/thread/qbasicatomic.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qatomic_bootstrap.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/thread/qatomic_bootstrap.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qgenericatomic.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/thread/qgenericatomic.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qatomic_cxx11.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/thread/qatomic_cxx11.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qatomic_msvc.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/thread/qatomic_msvc.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qglobalstatic.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qglobalstatic.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qmutex.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/thread/qmutex.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qnumeric.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qnumeric.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qversiontagging.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qversiontagging.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qobjectdefs_impl.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/kernel/qobjectdefs_impl.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qstring.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qstring.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qchar.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qchar.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qbytearray.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qbytearray.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qrefcount.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qrefcount.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qarraydata.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qarraydata.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qstringliteral.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qstringliteral.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qstringalgorithms.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qstringalgorithms.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qstringview.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qstringview.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qstringbuilder.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qstringbuilder.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qlist.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qlist.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qalgorithms.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qalgorithms.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qiterator.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qiterator.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qhashfunctions.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qhashfunctions.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qpair.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qpair.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qbytearraylist.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qbytearraylist.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qstringlist.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qstringlist.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qregexp.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qregexp.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qstringmatcher.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qstringmatcher.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qcoreevent.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/kernel/qcoreevent.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qscopedpointer.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qscopedpointer.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qmetatype.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/kernel/qmetatype.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qvarlengtharray.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qvarlengtharray.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qcontainerfwd.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qcontainerfwd.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qobject_impl.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/kernel/qobject_impl.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/QString \
		ChessInterface.h \
		moc_predefs.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/bin/moc
	/home/somas/Qt12_wasm/5.12.0/Src/qtbase/bin/moc $(DEFINES) --include /home/somas/ChessNewGeneration/ChessNewGeneration/moc_predefs.h -I/home/somas/Qt12_wasm/5.12.0/Src/qtbase/mkspecs/wasm-emscripten -I/home/somas/ChessNewGeneration/ChessNewGeneration -I/home/somas/Qt12_wasm/5.12.0/Src/qtdeclarative/include -I/home/somas/Qt12_wasm/5.12.0/Src/qtbase/include -I/home/somas/Qt12_wasm/5.12.0/Src/qtdeclarative/include/QtQuick -I/home/somas/Qt12_wasm/5.12.0/Src/qtbase/include/QtQuick -I/home/somas/Qt12_wasm/5.12.0/Src/qtdeclarative/include/QtQml -I/home/somas/Qt12_wasm/5.12.0/Src/qtbase/include/QtQml -I/home/somas/Qt12_wasm/5.12.0/Src/qtbase/include/QtGui -I/home/somas/Qt12_wasm/5.12.0/Src/qtbase/include/QtNetwork -I/home/somas/Qt12_wasm/5.12.0/Src/qtbase/include/QtCore -I/usr/include -I/usr/local/include ChessInterface.h -o moc_ChessInterface.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../Qt12_wasm/5.12.0/Src/qtbase/include/QtGui/QGuiApplication \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtGui/qguiapplication.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/gui/kernel/qguiapplication.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtGui/qtguiglobal.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/gui/kernel/qtguiglobal.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qglobal.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qglobal.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qconfig-bootstrapped.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qconfig-bootstrapped.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qconfig.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qconfig.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qtcore-config.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/qtcore-config.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qsystemdetection.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qsystemdetection.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qprocessordetection.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qprocessordetection.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qcompilerdetection.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qcompilerdetection.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qtypeinfo.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qtypeinfo.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qsysinfo.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qsysinfo.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qlogging.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qlogging.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qflags.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qflags.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qatomic.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/thread/qatomic.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qbasicatomic.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/thread/qbasicatomic.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qatomic_bootstrap.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/thread/qatomic_bootstrap.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qgenericatomic.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/thread/qgenericatomic.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qatomic_cxx11.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/thread/qatomic_cxx11.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qatomic_msvc.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/thread/qatomic_msvc.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qglobalstatic.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qglobalstatic.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qmutex.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/thread/qmutex.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qnumeric.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qnumeric.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qversiontagging.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qversiontagging.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtGui/qtgui-config.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/gui/qtgui-config.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qcoreapplication.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/kernel/qcoreapplication.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qstring.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qstring.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qchar.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qchar.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qbytearray.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qbytearray.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qrefcount.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qrefcount.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qnamespace.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/global/qnamespace.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qarraydata.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qarraydata.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qstringliteral.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qstringliteral.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qstringalgorithms.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qstringalgorithms.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qstringview.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qstringview.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qstringbuilder.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qstringbuilder.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qobject.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/kernel/qobject.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qobjectdefs.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/kernel/qobjectdefs.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qobjectdefs_impl.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/kernel/qobjectdefs_impl.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qlist.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qlist.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qalgorithms.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qalgorithms.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qiterator.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qiterator.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qhashfunctions.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qhashfunctions.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qpair.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qpair.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qbytearraylist.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qbytearraylist.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qstringlist.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qstringlist.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qregexp.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qregexp.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qstringmatcher.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qstringmatcher.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qcoreevent.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/kernel/qcoreevent.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qscopedpointer.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qscopedpointer.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qmetatype.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/kernel/qmetatype.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qvarlengtharray.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qvarlengtharray.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qcontainerfwd.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qcontainerfwd.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qobject_impl.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/kernel/qobject_impl.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qeventloop.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/kernel/qeventloop.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtGui/qwindowdefs.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/gui/kernel/qwindowdefs.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtGui/qwindowdefs_win.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/gui/kernel/qwindowdefs_win.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtGui/qinputmethod.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/gui/kernel/qinputmethod.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qlocale.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qlocale.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qvariant.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/kernel/qvariant.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qmap.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qmap.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qdebug.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/io/qdebug.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qhash.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qhash.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qtextstream.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/serialization/qtextstream.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qiodevice.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/io/qiodevice.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qvector.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qvector.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qpoint.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qpoint.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qset.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qset.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qcontiguouscache.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qcontiguouscache.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qsharedpointer.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qsharedpointer.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qshareddata.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qshareddata.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qsharedpointer_impl.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qsharedpointer_impl.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qsize.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/tools/qsize.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/include/QtQml/QQmlApplicationEngine \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/include/QtQml/qqmlapplicationengine.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/src/qml/qml/qqmlapplicationengine.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/include/QtQml/qqmlengine.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/src/qml/qml/qqmlengine.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qurl.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/io/qurl.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qurlquery.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/io/qurlquery.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/include/QtQml/qjsengine.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/src/qml/jsapi/qjsengine.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/include/QtQml/qjsvalue.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/src/qml/jsapi/qjsvalue.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/include/QtQml/qtqmlglobal.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/src/qml/qtqmlglobal.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtQml/qtqml-config.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/src/qml/qtqml-config.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtNetwork/qtnetworkglobal.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/network/kernel/qtnetworkglobal.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtNetwork/qtnetwork-config.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/network/qtnetwork-config.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/include/QtQml/qqmldebug.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/src/qml/debugger/qqmldebug.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/include/QtQml/qqml.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/src/qml/qml/qqml.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/include/QtQml/qqmlprivate.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/src/qml/qml/qqmlprivate.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/include/QtQml/qqmlparserstatus.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/src/qml/qml/qqmlparserstatus.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/include/QtQml/qqmlpropertyvaluesource.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/src/qml/qml/qqmlpropertyvaluesource.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/include/QtQml/qqmllist.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/src/qml/qml/qqmllist.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/qmetaobject.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/src/corelib/kernel/qmetaobject.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/include/QtQml/qqmlerror.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/src/qml/qml/qqmlerror.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/include/QtQml/QQmlContext \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/include/QtQml/qqmlcontext.h \
		../../Qt12_wasm/5.12.0/Src/qtdeclarative/src/qml/qml/qqmlcontext.h \
		ChessGame.h \
		Chessboard.h \
		Piece.h \
		ChessInterface.h \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/QObject \
		../../Qt12_wasm/5.12.0/Src/qtbase/include/QtCore/QString \
		Position.h \
		Player.h \
		Move.h \
		ChessPieces.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qtprojectfile.js_plugin_import.o: /home/somas/ChessNewGeneration/ChessNewGeneration/qtprojectfile.js_plugin_import.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtprojectfile.js_plugin_import.o /home/somas/ChessNewGeneration/ChessNewGeneration/qtprojectfile.js_plugin_import.cpp

qtprojectfile.js_qml_plugin_import.o: /home/somas/ChessNewGeneration/ChessNewGeneration/qtprojectfile.js_qml_plugin_import.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtprojectfile.js_qml_plugin_import.o /home/somas/ChessNewGeneration/ChessNewGeneration/qtprojectfile.js_qml_plugin_import.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_ChessInterface.o: moc_ChessInterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ChessInterface.o moc_ChessInterface.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/QtProjectFile/bin || mkdir -p $(INSTALL_ROOT)/opt/QtProjectFile/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/QtProjectFile/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/QtProjectFile/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/QtProjectFile/bin/ 


install_js_file: first FORCE
	@test -d $(INSTALL_ROOT)/opt/QtProjectFile/bin || mkdir -p $(INSTALL_ROOT)/opt/QtProjectFile/bin
	-$(QINSTALL_PROGRAM) /home/somas/ChessNewGeneration/ChessNewGeneration/QtProjectFile.js $(INSTALL_ROOT)/opt/QtProjectFile/bin/QtProjectFile.js

uninstall_js_file: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/QtProjectFile/bin/QtProjectFile.js
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/QtProjectFile/bin/ 


install: install_target install_js_file  FORCE

uninstall: uninstall_target uninstall_js_file  FORCE

FORCE:

